package entities

import "encoding/json"

type OrthancInstance struct {
	FileSize      int    `json:"FileSize"`
	FileUUID      string `json:"FileUuid"`
	ID            string `json:"ID"`
	IndexInSeries int    `json:"IndexInSeries"`
	MainDicomTags struct {
		AcquisitionNumber       string `json:"AcquisitionNumber"`
		ImageOrientationPatient string `json:"ImageOrientationPatient"`
		ImagePositionPatient    string `json:"ImagePositionPatient"`
		InstanceCreationDate    string `json:"InstanceCreationDate"`
		InstanceCreationTime    string `json:"InstanceCreationTime"`
		InstanceNumber          string `json:"InstanceNumber"`
		SOPInstanceUID          string `json:"SOPInstanceUID"`
	} `json:"MainDicomTags"`
	ParentSeries string `json:"ParentSeries"`
	Type         string `json:"Type"`
}

func (t *OrthancSimplfiedTags) String() string {
	b, _ := json.Marshal(t)
	return string(b)
}

type OrthancSimplfiedTags struct {
	AccessionNumber                   string      `json:"AccessionNumber"`
	AcquisitionDate                   string      `json:"AcquisitionDate"`
	AcquisitionNumber                 string      `json:"AcquisitionNumber"`
	AcquisitionTime                   string      `json:"AcquisitionTime"`
	AdditionalPatientHistory          string      `json:"AdditionalPatientHistory"`
	AngleOfFirstView                  string      `json:"AngleOfFirstView"`
	BiopsyPosition                    string      `json:"BiopsyPosition"`
	BiopsyRefLocation                 string      `json:"BiopsyRefLocation"`
	BiopsyTLocation                   string      `json:"BiopsyTLocation"`
	BitsAllocated                     string      `json:"BitsAllocated"`
	BitsStored                        string      `json:"BitsStored"`
	CellNumberAtTheta                 string      `json:"CellNumberAtTheta"`
	CellSpacing                       string      `json:"CellSpacing"`
	CenterACoordOfPlaneImage          string      `json:"CenterACoordOfPlaneImage"`
	CenterRCoordOfPlaneImage          string      `json:"CenterRCoordOfPlaneImage"`
	CenterSCoordOfPlaneImage          string      `json:"CenterSCoordOfPlaneImage"`
	Columns                           string      `json:"Columns"`
	ContentDate                       string      `json:"ContentDate"`
	ContentTime                       string      `json:"ContentTime"`
	ConvolutionKernel                 string      `json:"ConvolutionKernel"`
	CorrectedAfterglowTerms           string      `json:"CorrectedAfterglowTerms"`
	DASAdInput                        string      `json:"DASAdInput"`
	DASCalMode                        string      `json:"DASCalMode"`
	DASFpaGain                        string      `json:"DASFpaGain"`
	DASOutputSource                   string      `json:"DASOutputSource"`
	DASTriggerSource                  string      `json:"DASTriggerSource"`
	DataCollectionDiameter            string      `json:"DataCollectionDiameter"`
	DegreeOfRotation                  string      `json:"DegreeOfRotation"`
	DegreesOfAzimuth                  string      `json:"DegreesOfAzimuth"`
	DeltaStartTime                    string      `json:"DeltaStartTime"`
	DependantOnNumberOfViewsProcessed string      `json:"DependantOnNumberOfViewsProcessed"`
	DistanceSourceToDetector          string      `json:"DistanceSourceToDetector"`
	DistanceSourceToPatient           string      `json:"DistanceSourceToPatient"`
	DurationOfXrayOn                  string      `json:"DurationOfXrayOn"`
	EquipmentUID                      string      `json:"EquipmentUID"`
	Exposure                          string      `json:"Exposure"`
	ExposureTime                      string      `json:"ExposureTime"`
	FilterType                        string      `json:"FilterType"`
	FirstScanRAS                      string      `json:"FirstScanRAS"`
	FocalSpots                        string      `json:"FocalSpots"`
	FrameOfReferenceUID               string      `json:"FrameOfReferenceUID"`
	FullFidelity                      string      `json:"FullFidelity"`
	GantryDetectorTilt                string      `json:"GantryDetectorTilt"`
	GantryPeriod                      string      `json:"GantryPeriod"`
	GeneratorPower                    string      `json:"GeneratorPower"`
	HighBit                           string      `json:"HighBit"`
	HorizontalFrameOfReference        string      `json:"HorizontalFrameOfReference"`
	ImageActualDate                   string      `json:"ImageActualDate"`
	ImageFromWhichPrescribed          string      `json:"ImageFromWhichPrescribed"`
	ImageOrientationPatient           string      `json:"ImageOrientationPatient"`
	ImagePositionPatient              string      `json:"ImagePositionPatient"`
	ImageType                         string      `json:"ImageType"`
	InstanceCreationDate              string      `json:"InstanceCreationDate"`
	InstanceCreationTime              string      `json:"InstanceCreationTime"`
	InstanceNumber                    string      `json:"InstanceNumber"`
	InstitutionName                   string      `json:"InstitutionName"`
	KVP                               string      `json:"KVP"`
	LastScanRAS                       string      `json:"LastScanRAS"`
	Manufacturer                      string      `json:"Manufacturer"`
	ManufacturerModelName             string      `json:"ManufacturerModelName"`
	MaxOverrangesInAView              string      `json:"MaxOverrangesInAView"`
	MidScanFlag                       string      `json:"MidScanFlag"`
	MidScanTime                       string      `json:"MidScanTime"`
	Modality                          string      `json:"Modality"`
	NameOfPhysiciansReadingStudy      string      `json:"NameOfPhysiciansReadingStudy"`
	NoViewsRefChannelsBlocked         string      `json:"NoViewsRefChannelsBlocked"`
	NormalACoord                      string      `json:"NormalACoord"`
	NormalRCoord                      string      `json:"NormalRCoord"`
	NormalSCoord                      string      `json:"NormalSCoord"`
	NumberOfCellsInDetector           string      `json:"NumberOfCellsInDetector"`
	NumberOfOverranges                string      `json:"NumberOfOverranges"`
	NumberOfTriggers                  string      `json:"NumberOfTriggers"`
	OperatorsName                     string      `json:"OperatorsName"`
	OtherPatientIDs                   string      `json:"OtherPatientIDs"`
	PatientAge                        string      `json:"PatientAge"`
	PatientBirthDate                  string      `json:"PatientBirthDate"`
	PatientID                         string      `json:"PatientID"`
	PatientName                       string      `json:"PatientName"`
	PatientPosition                   string      `json:"PatientPosition"`
	PatientSex                        string      `json:"PatientSex"`
	PerformedProcedureStepDescription string      `json:"PerformedProcedureStepDescription"`
	PerformedProcedureStepID          string      `json:"PerformedProcedureStepID"`
	PerformedProcedureStepStartDate   string      `json:"PerformedProcedureStepStartDate"`
	PerformedProcedureStepStartTime   string      `json:"PerformedProcedureStepStartTime"`
	PerformingPhysicianName           string      `json:"PerformingPhysicianName"`
	PhotometricInterpretation         string      `json:"PhotometricInterpretation"`
	PixelData                         interface{} `json:"PixelData"`
	PixelPaddingValue                 string      `json:"PixelPaddingValue"`
	PixelRepresentation               string      `json:"PixelRepresentation"`
	PixelSpacing                      string      `json:"PixelSpacing"`
	PlaneType                         string      `json:"PlaneType"`
	PositionReferenceIndicator        string      `json:"PositionReferenceIndicator"`
	PrivateCreator                    string      `json:"PrivateCreator"`
	PrivateScanOptions                string      `json:"PrivateScanOptions"`
	ProductID                         string      `json:"ProductId"`
	ProtocolName                      string      `json:"ProtocolName"`
	RACoordOfTargetReconCentre        string      `json:"RACoordOfTargetReconCentre"`
	ReconPostProcessingFlag           string      `json:"ReconPostProcessingFlag"`
	ReconstructionDiameter            string      `json:"ReconstructionDiameter"`
	ReferenceChannels                 string      `json:"ReferenceChannels"`
	ReferencedImageSequence           []struct {
		ReferencedSOPClassUID    string `json:"ReferencedSOPClassUID"`
		ReferencedSOPInstanceUID string `json:"ReferencedSOPInstanceUID"`
	} `json:"ReferencedImageSequence"`
	ReferringPhysicianName    string      `json:"ReferringPhysicianName"`
	RescaleIntercept          string      `json:"RescaleIntercept"`
	RescaleSlope              string      `json:"RescaleSlope"`
	RescaleType               string      `json:"RescaleType"`
	RevolutionTime            string      `json:"RevolutionTime"`
	RotationDirection         string      `json:"RotationDirection"`
	Rows                      string      `json:"Rows"`
	SOPClassUID               string      `json:"SOPClassUID"`
	SOPInstanceUID            string      `json:"SOPInstanceUID"`
	SamplesPerPixel           string      `json:"SamplesPerPixel"`
	ScanFOVType               string      `json:"ScanFOVType"`
	ScanOptions               string      `json:"ScanOptions"`
	ScanPitchRatio            string      `json:"ScanPitchRatio"`
	ScoutType                 string      `json:"ScoutType"`
	SegmentNumber             string      `json:"SegmentNumber"`
	SeriesContrast            string      `json:"SeriesContrast"`
	SeriesDate                string      `json:"SeriesDate"`
	SeriesDescription         string      `json:"SeriesDescription"`
	SeriesFromWhichPrescribed string      `json:"SeriesFromWhichPrescribed"`
	SeriesInstanceUID         string      `json:"SeriesInstanceUID"`
	SeriesNumber              string      `json:"SeriesNumber"`
	SeriesTime                string      `json:"SeriesTime"`
	SingleCollimationWidth    string      `json:"SingleCollimationWidth"`
	SliceLocation             string      `json:"SliceLocation"`
	SliceThickness            string      `json:"SliceThickness"`
	SmartScanOnOffFlag        string      `json:"SmartScanOnOffFlag"`
	SoftwareVersions          string      `json:"SoftwareVersions"`
	SpacingBetweenSlices      string      `json:"SpacingBetweenSlices"`
	SpecificCharacterSet      string      `json:"SpecificCharacterSet"`
	SpiralPitchFactor         string      `json:"SpiralPitchFactor"`
	StartScanToXrayOnDelay    string      `json:"StartScanToXrayOnDelay"`
	StartTimeSecsInFirstAxial string      `json:"StartTimeSecsInFirstAxial"`
	StationName               string      `json:"StationName"`
	StudyDate                 string      `json:"StudyDate"`
	StudyDescription          string      `json:"StudyDescription"`
	StudyID                   string      `json:"StudyID"`
	StudyInstanceUID          string      `json:"StudyInstanceUID"`
	StudyTime                 string      `json:"StudyTime"`
	SuiteID                   string      `json:"SuiteId"`
	TableEndLocation          string      `json:"TableEndLocation"`
	TableFeedPerRotation      string      `json:"TableFeedPerRotation"`
	TableHeight               string      `json:"TableHeight"`
	TableSpeed                string      `json:"TableSpeed"`
	TableStartLocation        string      `json:"TableStartLocation"`
	TotalCollimationWidth     string      `json:"TotalCollimationWidth"`
	TotalSegmentsRequested    string      `json:"TotalSegmentsRequested"`
	TriggerFrequency          string      `json:"TriggerFrequency"`
	TriggerOnPosition         string      `json:"TriggerOnPosition"`
	UniqueImageIdentifier     interface{} `json:"UniqueImageIdentifier"`
	UnknownTagData            interface{} `json:"Unknown Tag & Data"`
	ViewCompressionFactor     string      `json:"ViewCompressionFactor"`
	VmaClip                   string      `json:"VmaClip"`
	VmaMamp                   string      `json:"VmaMamp"`
	VmaMod                    string      `json:"VmaMod"`
	WindowCenter              string      `json:"WindowCenter"`
	WindowValue               string      `json:"WindowValue"`
	WindowWidth               string      `json:"WindowWidth"`
	XRayTubeCurrent           string      `json:"XRayTubeCurrent"`
	XrayChain                 string      `json:"XrayChain"`
}
